language: r
cache:
  directories:
  - _bookdown_files
  - $HOME/.npm
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

pandoc_version: 2.1.1

r_packages:
  - devtools

env:
  global:
    - NETLIFY_SITE_ID=2690c16e-4eb9-4414-9c7a-20f663760cc6
    - RENV_CONFIG_REPOS_OVERRIDE=https://demo.rstudiopm.com/all/__linux__/xenial/latest

before_install:
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"

install:
  - Rscript -e 'old.packages(repos = Sys.getenv("RENV_CONFIG_REPOS_OVERRIDE"), lib.loc = .libPaths()[1])'

script:
  - Rscript -e "source('can_you_read_me.R')"
  - Rscript -e 'source("can_you_read_me.R"); bookdown::render_book("index.Rmd", quiet = TRUE)'

before_cache:
- nvm install stable
- npm install netlify-cli -g

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
      
      
      

