# Copying
```{r, echo=FALSE, warning=FALSE}
library(knitr)
```

##Copying the Stat 545 Book
We are going to copy the stat545 book which can be found here: https://stat545.com/

### Github and Rstudio Setup



1.Goto the [stat 545](https://github.com/rstudio-education/stat545) page  
2.Hit the button in the upper right corner, that says fork  
3.Go to your copy of stat 545    
4.Hit clone or download  
5.Go into Rstudio and create a new github project  
6.paste the link from your github fork into the Repository URL and hit create project.  


**Fix** You may initally get error messages, try deleting the .rprofile file inside of the renv folder.  
**Fix** You may be missing libraries. There is a package called renv that stores libraries differently in this repository. When you download the repo, you can type `.libpath` and you will notice that you now have two library paths instead of one. This is not a problem aslong as you restore the libraries with `renv::restore()`.

8. Type in the command `git remote add upstream https://github.com/rstudio-education/stat545` into the terminal prompt. This will create an upstream remote repo that can be updated and merged with our modified version.  

9. Type the command `git config rerere.enable true` into the terminal prompt. This will make it so that you will not be reprompted with the same merge conflicts that you have already addressed

### Getting a Free Url

We are getting a url name from [freenom](https://www.freenom.com/). 

**Warning**: The only catch with freenom is that these domains will only last for one year before expiring or costing money. Being free for one year is a gimmick to get you paying for a domain once you rely on people returning to that specific domain. You should probably find some other hosting if you plan on doing anything other than making a temp website. You should not circulate the website publically using freenom hosting. Luckily the proccess should be similar if you use other hosting.

1. Enter a url name
2. Check availability and find a url that is free
3. Click “Get it Now!”
4. Click Checkout
5. Select 12 Months @ FREE
6. Login or create an account
7. Complete the order

### Connecting the Github Repository to Netlify
This part of the tutorial has many working parts and won't work until the very end.

1. Hit new site from git
2. Login to your github account
3. Select the repo you forked

This will create a nonfunctioning netlify page. We are only doing this so that we have the netlify credentials nessisary to make travis-ci work.

### Adding Travis to Your Repo

Travis allows for continuous integration, the section on why we use travis can be read about in the maintenance section: \@ref(why-we-use-travis)

In this section we will setup the .travis.yml file so that it works in conjunction with freenom and netlify

1. Sign up for travis ci account and activate on page of interest (note need pictures for this)
2. Find pre-existing .travis.yml file
3. Delete it manually, commit the change, and push  
4. Undo the manual delete, commit the change, and push

This must be done because travis does not activate until it sees you push a .travis.yml file. This is the indicator that the service looks for. 

5. Find API ID in netlify (under site information) and copy that into NETLIFY_SITE_ID in the travis file

6. Create Netlify authentication token by going to this link: https://app.netlify.com/user/applications#personal-access-tokens 

7. Go into settings for your travis branch and copy and past your auth key into an environment variable you name NETLIFY_AUTH_TOKEN
**Warning** you can set NETLIFY_AUTH_TOKEN in your yml file but this will expose it on github

### Adding the Custom Domain

1. Go to netlify 
  - enter the url of your custom domain into step 2 “adding a custom domain”
2. Go to freenom
  - Goto my domains
  - Click on manage domain next to your domain of interest
  - Go to management tools
3. Goto netlify
  - Goto check dns configuration
  - Goto setup dns for x domain
  - Skip records
  - Copy all the name servers
4. Goto freenom
  - Goto management tools 
  - Goto name servers
  - Click on custom name servers
  - Copy and paste in all the name servers

### Last Push
Once you have finished everything above you can push your changes and see them unfold on the travis homepage. It will take some time to run your code on travis, but once it is done you should see your changes on your website. If there are any errors you will be able easily spot those errors in the travis logs

## ModernDive
Setting up moderndive is similar to setting up stat545. Moderndive does not use netlify, and instead uses github pages. Because we use netlify we must modify moderndive to work correctly with our tools. I will be taking files from stat545 and using them to host the website. I also think that it is worth mentioning that by using the netlify approach we will avoid using a more complicated system that relys on bash files and other odd dependencies.




