# What Every File Does

## Stat545 Support Files
### renv
where all the stat545 libs are stored. I want to get as many libraries into this as possible for faster load times.
## MD Support Files
## dsbook Support Files

### _common.R
Typically common files are supposed to be put at the top of files using the source function to add libraries, functions, and misc that are frequently called

### 
## My Files

### _lazygit.sh
If you run thsi file with the command `./_lazygit.sh "message"` you will add, commit, and push all in one line

### _copy.sh
Because of how travis doesn't give bookdown the ability to see into submodules when submodules are off, I used this bashfile to move all of the files that would be inside of the submodules to folders that the index file can see while running in travis.

### Static folders
These are the folders that _copy.sh moves files to

## Native Files

### index.Rmd
This is the first file in bookdown and it has many settings at the top that control how the book is made

### _bookdown.yml
This files controls where chapters go and can control scripting before chapters

### .travis.yml
This file controls the commands that are run in travis

### _output.yml
This file controls the asthetic of the bookdown output

### style.css
Your typical css

### functions.R
This file contains a bunch of commonly used functions that need to run before the rest of the book runs

### GovImages
has images for gov logo

## Need to check

### _includes
### _redirects
### bib
this is probably the bib folder for MD, I don't think we need it
### book.bib
This file is a bibliography
### CONDUCT.md
### data
This is nessisary for something don't delete. I will find out what it is used for later
### Description
### docs
This is a MD file, md uses docs for some reason
### figure
folder of figures
### img
has images need to figure out for what files dont delete
### images
has more images need to figure out
### krantz.cls
is a formatting files
### latex
formatting
### labs.html
### packages.bib
records what packages were used, need to throw out
### pdf_build_from_text.R
too afraid to throw away. I think it is only relevent if you work with pdfs
### purl.R
Puts all of your code into scripts. too afraid to delete
### rds
data files
### rds_old
data files that I shouldn't care about
### supporting docs
important need to track down origin