# Do This Preceptor

1. Start by making a copy of this repository: https://github.com/moderndive/ModernDive_book

2. Download the repo to your computer

3. Type in the command `git remote add upstream https://github.com/moderndive/ModernDive_book` into the terminal prompt. This will create an upstream remote repo that can be updated and merged with our modified version. __You don't need to do this step now.__

4. Type the command `git config rerere.enable true` into the terminal prompt. This will make it so that you will not be re-prompted with the same merge conflicts that you have already addressed. __You don't need to do this step now__

### Getting a Free Url

We are getting a url name from [freenom](https://www.freenom.com/). 

**Warning**: The only catch with freenom is that these domains will only last for one year before expiring or costing money. Being free for one year is a gimmick to get you paying for a domain once you rely on people returning to that specific domain. You should probably find some other hosting if you plan on doing anything other than making a temp website. You should not circulate the website publically using freenom hosting. Luckily the proccess should be similar if you use other hosting.

1. Enter a url name
2. Check availability and find a url that is free
3. Click “Get it Now!”
4. Click Checkout
5. Select 12 Months @ FREE
6. Login or create an account
7. Complete the order

### Connecting the Github Repository to Netlify
This part of the tutorial has many working parts and won't work until the very end.

1. Hit new site from git
2. Login to your github account
3. Select the repo you forked

This will create a nonfunctioning netlify page. We are only doing this so that we have the netlify credentials necessary to make travis-ci work. We will get back to it.

### Adding Travis to Your Repo

Travis allows for continuous integration, the section on why we use travis can be read about in the maintenance section: \@ref(why-we-use-travis)

In this section we will setup the .travis.yml file so that it works in conjunction with freenom and netlify

1. Sign up for travis ci account.
2. In terminal type these commands seperately
`mv .travis.yml _includes`

`git add .`

`git commit -m "travis setup"`

`git push`

`mv _includes/.travis.yml .travis.yml`

`git add .`

`git commit -m "travis setup"`

`git push`


You need to do this file manipulation because travis does not activate until it sees you push a .travis.yml file. This is the indicator that the service looks for. Here is a link for explaination: https://docs.travis-ci.com/user/tutorial/

5. You will have a travis file that intially looks like this
```
language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - devtools

r_github_packages:
  - moderndive/moderndive
  - tidymodels/infer

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
#  - ./_deploy.sh

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep-history: true
  github_token: $MODERNDIVE_GITHUB_PAT
  repo: moderndive/moderndive_book
  # For testing purposes only
#  target_branch: deploy-from-travis
  # Switch back to gh-pages after getting the build to work
  # to deploy bookdown webpages
  target_branch: gh-pages
```

You will need to modify your travis so that it looks like this
```
language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - devtools

env:
  global:
    - NETLIFY_SITE_ID=ba0a8045-469c-4ea3-bd7c-9aedab996798

before_install:
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

before_cache:
- nvm install stable
- npm install netlify-cli -g

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
```

6. Create Netlify authentication token by going to this link: https://app.netlify.com/user/applications#personal-access-tokens 

7. Go into settings for your travis branch and copy and past your auth key into an environment variable you name NETLIFY_AUTH_TOKEN
**Warning** you can set NETLIFY_AUTH_TOKEN in your yml file but this will expose it on github

### Adding the Custom Domain

1. Go to netlify 
  - enter the url of your custom domain into step 2 “adding a custom domain”
2. Go to freenom
  - Goto my domains
  - Click on manage domain next to your domain of interest
  - Go to management tools
3. Goto netlify
  - Goto check dns configuration
  - Goto setup dns for x domain
  - Skip records
  - Copy all the name servers
4. Goto freenom
  - Goto name servers in management tools
  - Click on custom name servers
  - Copy and paste in all the name servers


### _bookdown.yml Chapters

Your `_bookdown.yml` file will look like this initally
```
book_filename: "ModernDive"
output_dir: "docs"
# clean: [bib/packages.bib]
delete_merged_file: true
# Need to update this if any changes to filenames now
rmd_files:
  html: [
    "index.Rmd",
    "00-foreword.Rmd",
    "00-preface.Rmd",
    "01-getting-started.Rmd",
    "02-visualization.Rmd",
    "03-wrangling.Rmd",
    "04-tidy.Rmd",
    "05-regression.Rmd",
    "06-multiple-regression.Rmd",
    "07-sampling.Rmd",
    "08-confidence-intervals.Rmd",
    "09-hypothesis-testing.Rmd",
    "10-inference-for-regression.Rmd",
    "11-tell-your-story-with-data.Rmd",
    "91-appendixA.Rmd",
    "92-appendixB.Rmd",
    "93-appendixC.Rmd",
    "94-appendixD.Rmd",
    "95-appendixE.Rmd",
    "99-references.Rmd"
    ]
  latex: [
    "index.Rmd",
    "00-foreword.Rmd",
    "00-preface.Rmd",
    "01-getting-started.Rmd",
    "02-visualization.Rmd",
    "03-wrangling.Rmd",
    "04-tidy.Rmd",
    "05-regression.Rmd",
    "06-multiple-regression.Rmd",
    "07-sampling.Rmd",
    "08-confidence-intervals.Rmd",
    "09-hypothesis-testing.Rmd",
    "10-inference-for-regression.Rmd",
    "11-tell-your-story-with-data.Rmd",
    "91-appendixA.Rmd",
    "95-appendixE.Rmd",
    "99-references.Rmd"
    ]
language:
  label:
    fig: "FIGURE "
    tab: "TABLE "
  ui:
    edit: "Edit"
    chapter_name: "Chapter "
```
You need to change it so that it looks like this:
```
book_filename: "ModernDive"
delete_merged_file: true
rmd_files:[ "index.Rmd",
            "00-foreword.Rmd",
            "00-preface.Rmd",
            "01-getting-started.Rmd",
            "02-visualization.Rmd",
            "03-wrangling.Rmd",
            "04-tidy.Rmd",
            "05-regression.Rmd",
            "06-multiple-regression.Rmd",
            "07-sampling.Rmd",
            "08-confidence-intervals.Rmd",
            "09-hypothesis-testing.Rmd",
            "10-inference-for-regression.Rmd",
            "11-tell-your-story-with-data.Rmd",
            "91-appendixA.Rmd",
            "92-appendixB.Rmd",
            "93-appendixC.Rmd",
            "94-appendixD.Rmd",
            "95-appendixE.Rmd",
            "99-references.Rmd"]
language:
  label:
    fig: "FIGURE "
    tab: "TABLE "
  ui:
    edit: "Edit"
    chapter_name: "Chapter "
```

### Checking if everything is working
Once you have finished everything above you can push your changes and see them unfold on the travis homepage. It will take some time to run your code on travis, but once it is done you should see your changes on your website. If there are any errors you will be able easily spot those errors in the travis logs

To see if everything is working this link:
https://travis-ci.org/davidkane9/ModernDive_book



