# Recreating the three in one textbook

## Submodule Setup

Start by making a copy of this repository: https://github.com/NicholasDow/BookMakingGuide

Type `renv::restore()` in the command line to update all of your packages.

The process to make a submodule is the same for the three books we use, but I included all the commands for convenience.

Type `git submodule add https://github.com/rstudio-education/stat545.git`
to add a folder full of the files that make the stat545 book. Go into the submodule with `cd /stat545` and initialize it with `git submodule init`. Then type `git submodule update` to get the submodule to point to the most recent commit.

Type `git submodule add https://github.com/moderndive/ModernDive_book.git` to add MD. Go into the submodule with `cd /ModernDive_book` and initialize it with `git submodule init`.Then type `git submodule update` to get the submodule to point to the most recent commit.

Type `git submodule add https://github.com/rafalab/dsbook.git` to add dsbook. Go into the submodule with `cd /dsbook` and initialize it with `git submodule init`Then type `git submodule update` to get the submodule to point to the most recent commit.

if you want to make changes to the submodule then you must go into the submodule with `cd name/of/dir`. Each submodule is it's own repository, so anything you can do in a normal repo, you can do inside of a submodule.

you will also want to go into `.travis.yml` and add:
```
git:
  submodules: false
```
so that travis does not clone and overwrite the submodules every time it runs in the command line.

##Setting up the Website
This process is pretty much the same as in the copying chapter. Feel free to ignore this if you already know how to setup the website. 
### Getting a Free Url

We are getting a url name from [freenom](https://www.freenom.com/). 

**Warning**: The only catch with freenom is that these domains will only last for one year before expiring or costing money. Being free for one year is a gimmick to get you paying for a domain once you rely on people returning to that specific domain. You should probably find some other hosting if you plan on doing anything other than making a temp website. You should not circulate the website publically using freenom hosting. Luckily the proccess should be similar if you use other hosting.

1. Enter a url name
2. Check availability and find a url that is free
3. Click “Get it Now!”
4. Click Checkout
5. Select 12 Months @ FREE
6. Login or create an account
7. Complete the order

### Connecting the Github Repository to Netlify
This part of the tutorial has many working parts and won't work until the very end.

1. Hit new site from git
2. Login to your github account
3. Select the repo you forked

This will create a nonfunctioning netlify page. We are only doing this so that we have the netlify credentials nessisary to make travis-ci work.

### Adding Travis to Your Repo

Travis allows for continuous integration, the section on why we use travis can be read about in the maintenance section: \@ref(why-we-use-travis)

In this section we will setup the .travis.yml file so that it works in conjunction with freenom and netlify

1. Sign up for travis ci account and activate on page of interest (note need pictures for this)
2. Find pre-existing .travis.yml file
3. Delete it manually, commit the change, and push  
4. Undo the manual delete, commit the change, and push

This must be done because travis does not activate until it sees you push a .travis.yml file. This is the indicator that the service looks for. 

5. Find API ID in netlify (under site information) and copy that into NETLIFY_SITE_ID in the travis file

6. Create Netlify authentication token by going to this link: https://app.netlify.com/user/applications#personal-access-tokens 

7. Go into settings for your travis branch and copy and past your auth key into an environment variable you name NETLIFY_AUTH_TOKEN
**Warning** you can set NETLIFY_AUTH_TOKEN in your yml file but this will expose it on github

### Adding the Custom Domain

1. Go to netlify 
  - enter the url of your custom domain into step 2 “adding a custom domain”
2. Go to freenom
  - Goto my domains
  - Click on manage domain next to your domain of interest
  - Go to management tools
3. Goto netlify
  - Goto check dns configuration
  - Goto setup dns for x domain
  - Skip records
  - Copy all the name servers
4. Goto freenom
  - Goto management tools 
  - Goto name servers
  - Click on custom name servers
  - Copy and paste in all the name servers
  
## Using Stat545 and Moderndive Pages
You will have two folders with all the files from Stat545 and Moderndive. You can add the .Rmd files to your main bookdown book by going into the `_bookdown.yml` file and adding the paths of the .Rmd files from these third parties to the rmd_files section. 

First add `rmd_subdir: ["stat545", "ModernDive_book"]` so that these directories are searchable. You will not be able to use subdirectories unless you set `new_session: no` inside of your `_bookdown.yml`. This is because of rendering differences that you can read about here: https://bookdown.org/yihui/bookdown/new-session.html

You can also add the name of the file you want to add to the chapter to the list of rmd_files.

For example to add the file on installing from stat545 we would add the line between >>> and <<< to the rmd_files item:

```
rmd_files: ["index.Rmd", 
  "01-Introduction.Rmd", 
  "02-Setup.Rmd", 
  "03-From-Scratch.Rmd",
  "04-Copying.Rmd",
  "05-Two-Source-Github.Rmd",
  "06-Maintenance.Rmd",
  >>>
  "stat545/01_install.Rmd"]
  <<<
```

**Warning** In order to run files from a subdirectory you must have all of the support files in the same directory as the `index.Rmd` this will hopefully be fixed in the future, but for now it is an inconvenient feature of how the bookdown code is written. In order to make this easier to deal with you can create this bash script to get all of the support files:
```
```

Please note that if there are new support files added to the modderndive or stat545 texts, you will have to manually add them to the bash script or manually move them into the directory with the `index.rmd` file. 

Another thing that you must do is add all the names of the packages that 

## How to update the submodules
If we want to update any of the files inside of the submodule we must run this command to specifically merge the files, otherwise all of our work wil be overwritten.

First go into the submodule folder `cd \stat545` or `cd \ModernDive_book`. then checkout the stable branch with `git checkout master`. While you are in each submodule enable rerere with the command `git config rerere.enable true`. This will make it so that you don't have to resolve the same merge conflict twice. 

If you have set all of this the first time all you have to do every time you want to update the submodule is first:

`git submodule update --remote --merge`, this will make the submodule point at the most recent itteration.

`git add .`
`git commit -m "message"`
`git merge origin/master`

you might get issues with the length of names, if this is the case
`git config --system core.longpaths true`
This is a protected setting so you need to open a seperate terminal with admin permissions and enter the git command.

If you get merge conflicts then either manually resolve the conflicts or use `git mergetool`

then run these commands again

`git add .`
`git commit -m "message"`
`git merge origin/master`


This is a part of the workflow.

THere should be a chapter on the process of making edits



