# Making a Book using GitHub Pages

This is a guide to making the simplest possible book while using Github pages to host the result.

First, read [the introduction](https://pages.github.com/) to Github Pages. But don't be in a rush to do anything. In particular, I think the instructions are misleading since they suggest that you can only host a site for which the names match your user (or organization?) name. That is, I thought the only allowed project name for me (davidkane9) was davidkane9.github.io. But that is not true. Even worse, if you use that name then the ability to use the docs/ directory goes away. Very confusing!

Second, read Sean Kross's [guide](http://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html) to using Bookdown. This is very good, and I think can form the framework of the book.

Steps:

1) Create a new (empty) repo named whatever you like. Let's go with "book_test". This can be in whatever organization you like, I think. (At some point, we might need to create a new organization to hold the book (like [ModernDive](https://github.com/moderndive/moderndive.)), but not today.) 

2) Connect this repo to your computer. 

3) Download a zip file of Kross's [repo](https://github.com/seankross/bookdown-start). At some point, I would like to understand the details about why all these files are necessary. Unzip the contents wherever you downloaded it.

(**Note** Is it worth mentioning we could just fork and pull instead of steps 1-4, if we only want to make one bookdown book?)

> At some point, I would like to understand the details about why all these files are necessary. Unzip the contents wherever you downloaded it.

Nick's Response  
#### docs  
- Directory where bookdown sends all of it's output files (ie html) for GH to deploy  
#### .gitignore, .Rmd chapters, README.md, book.bib  
- Self explainitory  
#### _bookdown.yml  
- Controls ordering `rmd_files`, composition `new_session`, and output directory `output_dir` of chapters  
#### _output.yml  
- Controls Styling of book  
- `collapse: subsection` or `collapse: section`  
- Can control what images and html are in the header. We can add the icon using this  
- Controls different output formats: `bookdown::pdf_book`, `bookdown::epub_book`, and so on  
#### index.Rmd  
- Top of document has options for appearance and composition in html. See here: https://bookdown.org/yihui/bookdown/html.html  
#### preamble.tex and style.css  
- For text and html styling  

4) Move the contents (which won't include the highest bookdown-start-master/ directory) into your repo on the computer. Something like: `cp -r  ~/Downloads/bookdown-start-master/* .` from the Terminal window inside your new project. In other words, you need (I think) all the files to be at the highest possible level.

(**Note** I tried some other methods including `git clone gitseankrossurl .` but had issues because of the prexisting git history and files in the directory. I also had issues using the cp method. There are ways to ignore the git files but to make this possible, but it means copying and pasting a cryptic line of code)

4) Edit the _bookdown.yml file to change `repo: https://github.com/seankross/bookdown-start` to the url of your repo. Without this change, the book will not appear. Nor will you get an error.

5) Check everything in and push it. (Feel free to do whatever fussing you usualling like to do. For example, I modify the .gitignore so that the .Rproj file is not pushed.)

6) Go to Settings for this new repo (mine is at GOV-1005-Spring-2020/book) and scroll down to where it says Github Pages. Click on the drop down menu for source and select Master branch docs/ folder. (This is the step that does not work if you used davidkane9/davidkane9.github.io as the instructions seem to suggest you ought to. For some reason, you can't change these setting at all in that case.) (**Note** << I am little confused by the comment here.)

7) Everything works! Notice that the Kross repo has already populated the docs/ directory with the necessary html files. You now have a book located at https://davidkane9.github.io/book_test/, or whatever user/organization and repo name you used.

(**Note** https://username.github.io/repo-name/.)

8) Now you can edit the book. I recommend you start by making the other edits [recommended by Kross](http://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html). Then, you rebuild it using the "Build Book" button from the Build pane (which creates new html files in the docs/ directory) and then push the changes.  They will automatically appear at the Github Pages url. No need for Netifly or any other hosting service. (Note that it seems like you need to close and then open the project in order for the Build pane to appear. Presumably, there is a cooler way of letting R know that you are working on a book.)

(**Note** `bookdown::render_book('index.Rmd')` for whole book)

(**Note** `preview_chapter()` for single chapters) but as Yihui says: 
>One downside of previewing a chapter is that the cross-references to other chapters will not work, since bookdown knows nothing about other chapters in this case. That is a reasonably small price to pay for the gain in speed. Since previewing a chapter only renders the output for that specific chapter, you should not expect that the content of other chapters is correctly rendered as well. For example, when you navigate to a different chapter, you are actually viewing the old output of that chapter (which may not even exist).

<!-- A lot of MD chapters probably won't work because of how much cross-referencing there is. A solution to this is to add a `common.R` file to each chapter with `source('common.R')`, but this might be more trouble than using travis. Tell me if you want to do this. -->

9) In this step we are going to copy in the MD Repo, specifically excluding files that we don't need. You should be in the directory with your `index.Rmd` file when issuing these commands

  + `git clone https://github.com/moderndive/ModernDive_book.git` __This line clones the repository__

  + `shopt -s extglob` __This line enables regular expressions to be used in bash commands__

  + `cp -r ./ModernDive_book/!(docs|.DS_store|.git|*.Rproj|previous_versions|.travis.yml|_build.sh|_deploy.sh) .` __This line copies all the files that are needed into the main directory. Without the shopt command we couldn't use !(docs|...) to reference files__
  
  + `rm -r ./ModernDive_book` __This removes the directory__


10) Go into `_bookdown.yml` and change the repo line so that it refers to your directory `repo: https://github.com/Nameofuser/nameofrepo`. 

11) Run the command `bookdown::clean_book(TRUE); bookdown::render_book('index.Rmd', 'bookdown::gitbook');` to get a version of the book's html files written into your docs folder. This will overwrite the html files that were previously in the docs folder.

12) Push the new html files, and GH will render a website from them.