# GH pages docs folder method

1) Create a new (empty) repo named whatever you like. Let's go with "book_test". This can be in whatever organization you like, I think. (At some point, we might need to create a new organization to hold the book (like [ModernDive](https://github.com/moderndive/moderndive.)), but not today.) 

2) Connect this repo to your computer. 

3) Go to Settings for this new repo on github (mine is at GOV-1005-Spring-2020/book) and scroll down to where it says Github Pages. Click on the drop down menu for source and select Master branch docs/ folder. (This is the step that does not work if you used davidkane9/davidkane9.github.io as the instructions seem to suggest you ought to. For some reason, you can't change these setting at all in that case.) (**Note** << I am little confused by the comment here.)

<!-- A lot of MD chapters probably won't work because of how much cross-referencing there is. A solution to this is to add a `common.R` file to each chapter with `source('common.R')`, but this might be more trouble than using travis. Tell me if you want to do this. -->

4) In this step we are going to copy in the MD Repo, specifically excluding files that we don't need. You should be in the directory with your `index.Rmd` file when issuing these commands

  + `git clone https://github.com/moderndive/ModernDive_book.git` __This line clones the repository__

  + `shopt -s extglob` __This line enables regular expressions to be used in bash commands__

  + `cp -r ./ModernDive_book/!(docs|.DS_store|.git|*.Rproj|previous_versions|.travis.yml|_build.sh|_deploy.sh) .` __This line copies all the files that are needed into the main directory. Without the shopt command we couldn't use !(docs|...) to reference files__
  
  + `rm -r ./ModernDive_book` __This removes the directory__


<!-- 10) Go into `_bookdown.yml` and change the repo line so that it refers to your directory `repo: https://github.com/Nameofuser/nameofrepo`.  -->

5) Run the command `bookdown::clean_book(TRUE); bookdown::render_book('index.Rmd', 'bookdown::gitbook');` to get a version of the book's html files written into your docs folder. This will overwrite the html files that were previously in the docs folder.

(**Note** `bookdown::render_book('index.Rmd')` to render the whole book)

(**Note** `preview_chapter()` for single chapters) but as Yihui says: 
>One downside of previewing a chapter is that the cross-references to other chapters will not work, since bookdown knows nothing about other chapters in this case. That is a reasonably small price to pay for the gain in speed. Since previewing a chapter only renders the output for that specific chapter, you should not expect that the content of other chapters is correctly rendered as well. For example, when you navigate to a different chapter, you are actually viewing the old output of that chapter (which may not even exist).

6) Push the new html files, and GH will render a website from them.