--- 
title: "Nick's Bookmaking Guide"
author: "Nicholas Dow"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: NicholasDow/BookMakingGuide
url: 'http\://bookdown.ml/bookdown-guide/'
description: "Everything you need (and nothing more) to start a bookdown book."
---

# Preface {-}

This book will show you how to make and maintain a bookdown book made out of [stat545](https://stat545.com/),[ModernDive](https://moderndive.com/), and your own **.Rmd** files.


If you have any issues my email is [dow@college.harvard.edu](mailto:dow@college.harvar), I will try to fix those issues as soone as possible.

Make something here about what each chapter does

Delete below

The text displayed in this file is from index.Rmd.

This book will show you

1. How to make a website using netifly and a domain
2. How to make a bookdown book using the bare minimum boiler plate code
3. How to integrate travis into a netifly bookdown book and how to create a static website using netifly
4. How to maintain the bookdown book should you copy from another source
5. Tricks to make all of this easier

^^^ need to rewrite this part
Should talk about how every time you push changes to github you will be able to see those changes after a while because of travis

should also explain how travis lets you check for errors in your code when it doesn't run correctly. Should also talk about how it takes some time

